### ISSUE TITLE
规则复杂，更简单的规则使用方式

### ISSUE THREAD

**Issue by xcodebuild** [iproxy-org/iproxy#2]
搞个 UI 过于复杂，考虑到使用者大多为开发者，最好能提供类似 snippets 的东西，开发者照着改改就 ok

**Comment by ahonn** [comment]
可以考虑用类似 notion 斜杠后选择的交互方式

![image](https://user-images.githubusercontent.com/9718515/54583997-ff258980-4a50-11e9-8476-d0f89cd7510d.png)

**Comment by xcodebuild** [comment]
@ahonn 好主意，可以在新建规则的默认规则里让用户知道有 / 这么个用法

**Comment by xcodebuild** [comment]
![image](https://user-images.githubusercontent.com/5436704/54660116-fb0c7100-4b0f-11e9-91bd-e0db5eb2b822.png)

Fixed in 2.0.3
